In [1]:
import pandas as pd 
from pathlib import Path 
from datetime import datetime


DIR_PATH = Path.cwd().parent
DATA_PATH = DIR_PATH / "database"

df = pd.read_csv(DATA_PATH / "ventas_datastore.csv")

df

,id_orden,fecha,producto,categoria,precio_unitario,cantidad,canal,ciudad,metodo_pago,total_venta,fecha_str
0,1001,2024-11-23,Gorra snapback,Accesorios,17474.01,4.0,Shopify,Santiago,Transferencia,69896.04,23/11/2024
1,1002,2024-02-27,Gorra snapback,Accesorios,16218.56,5.0,MercadoLibre,Madrid,Tarjeta crédito,81092.80,27/02/2024
2,1003,2024-01-13,Gorra snapback,Accesorios,19404.71,3.0,WooCommerce,Córdoba,Transferencia,58214.13,13/01/2024
3,1004,2024-05-20,Remera básica,Ropa,14058.47,5.0,Tiendanube,Mendoza,Transferencia,70292.35,20/05/2024
4,1005,2024-05-05,Vestido floral,Ropa,36894.45,5.0,WooCommerce,Bogotá,Efectivo,184472.25,05/05/2024
...,...,...,...,...,...,...,...,...,...,...,...
5095,4602,2024-08-19,Short deportivo,Ropa,21004.67,5.0,MercadoLibre,Rosario,Efectivo,105023.35,19/08/2024
5096,1008,2024-02-22,Remera básica,Ropa,13754.23,3.0,WooCommerce,Buenos Aires,Efectivo,41262.69,22/02/2024
5097,3915,2024-07-08,Cinturón cuero,Accesorios,24780.33,3.0,MercadoLibre,Mar del Plata,Efectivo,74340.99,08/07/2024
5098,3957,2024-05-13,Gorra snapback,Accesorios,18051.12,4.0,Tiendanube,Córdoba,Tarjeta crédito,72204.48,13/05/2024
5099,1533,2024-06-09,Gorra snapback,Accesorios,17595.48,2.0,WooCommerce,Lima,Tarjeta débito,35190.96,09/06/2024

In [2]:
df.head(10)

,id_orden,fecha,producto,categoria,precio_unitario,cantidad,canal,ciudad,metodo_pago,total_venta,fecha_str
0,1001,2024-11-23,Gorra snapback,Accesorios,17474.01,4.0,Shopify,Santiago,Transferencia,69896.04,23/11/2024
1,1002,2024-02-27,Gorra snapback,Accesorios,16218.56,5.0,MercadoLibre,Madrid,Tarjeta crédito,81092.80,27/02/2024
2,1003,2024-01-13,Gorra snapback,Accesorios,19404.71,3.0,WooCommerce,Córdoba,Transferencia,58214.13,13/01/2024
3,1004,2024-05-20,Remera básica,Ropa,14058.47,5.0,Tiendanube,Mendoza,Transferencia,70292.35,20/05/2024
4,1005,2024-05-05,Vestido floral,Ropa,36894.45,5.0,WooCommerce,Bogotá,Efectivo,184472.25,05/05/2024
5,1006,2024-04-24,Zapatillas running,Calzado,78222.74,2.0,MercadoLibre,Bogotá,Transferencia,156445.48,24/04/2024
6,1007,2024-03-12,Cinturón cuero,Accesorios,24960.23,3.0,MercadoLibre,Bogotá,Tarjeta débito,74880.69,12/03/2024
7,1008,2024-02-22,Remera básica,Ropa,13754.23,3.0,WooCommerce,Buenos Aires,Efectivo,41262.69,22/02/2024
8,1009,2024-12-12,Zapatillas running,Calzado,85243.42,3.0,WooCommerce,Mar del Plata,Efectivo,255730.26,12/12/2024
9,1010,2024-10-06,Buzo hoodie,Ropa,51190.82,5.0,Shopify,Rosario,Tarjeta crédito,255954.10,06/10/2024

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5100 entries, 0 to 5099
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_orden         5100 non-null   int64
 1   fecha            5100 non-null   str
 2   producto         5051 non-null   str
 3   categoria        5100 non-null   str
 4   precio_unitario  5100 non-null   float64
 5   cantidad         5084 non-null   float64
 6   canal            5050 non-null   str
 7   ciudad           5050 non-null   str
 8   metodo_pago      5050 non-null   str
 9   total_venta      5100 non-null   float64
 10  fecha_str        5100 non-null   str
dtypes: float64(3), int64(1), str(7)
memory usage: 806.4 KB

In [4]:
df.describe()

          id_orden  precio_unitario     cantidad    total_venta
count  5100.000000      5100.000000  5084.000000    5100.000000
mean   3494.282549     37580.999666     2.975020  115495.648447
std    1443.942078     24468.884357     1.458578   97763.959457
min    1001.000000     -4775.121138    -1.000000    7207.580000
25%    2242.750000     17579.802500     2.000000   42105.187500
50%    3492.500000     30835.780000     3.000000   81110.985000
75%    4742.250000     54322.122500     4.000000  165036.780000
max    6000.000000     93495.010000     5.000000  465717.700000

In [5]:
df.isnull().sum()

id_orden            0
fecha               0
producto           49
categoria           0
precio_unitario     0
cantidad           16
canal              50
ciudad             50
metodo_pago        50
total_venta         0
fecha_str           0
dtype: int64

### Corrección nulos de productos

In [6]:
df_productos_nulos = df.loc[df["producto"].isnull()]
df_productos_nulos

,id_orden,fecha,producto,categoria,precio_unitario,cantidad,canal,ciudad,metodo_pago,total_venta,fecha_str
157,1158,2024-02-27,NaN,Accesorios,24742.410000,5.0,MercadoLibre,Mendoza,Tarjeta débito,123712.05,27/02/2024
175,1176,2024-07-10,NaN,Calzado,91294.350000,2.0,MercadoLibre,Santiago,Tarjeta crédito,182588.70,10/07/2024
240,1241,2024-05-01,NaN,Ropa,20982.690000,3.0,MercadoLibre,Santiago,Efectivo,62948.07,01/05/2024
271,1272,2024-05-07,NaN,Ropa,38785.030000,1.0,Tiendanube,Córdoba,Tarjeta crédito,38785.03,07/05/2024
277,1278,2024-08-04,NaN,Accesorios,7269.980000,3.0,Shopify,Buenos Aires,Efectivo,21809.94,04/08/2024
453,1454,2024-06-30,NaN,Accesorios,7550.250000,5.0,Shopify,Santiago,Tarjeta débito,37751.25,30/06/2024
570,1571,2024-04-19,NaN,Ropa,40620.750000,2.0,Shopify,Ciudad de México,Transferencia,81241.50,19/04/2024
696,1697,2024-06-21,NaN,Ropa,37665.580000,4.0,MercadoLibre,Córdoba,Tarjeta débito,150662.32,21/06/2024
810,1811,2024-10-02,NaN,Ropa,15811.170000,4.0,MercadoLibre,Mar del Plata,Tarjeta débito,63244.68,02/10/2024
929,1930,2024-02-28,NaN,Ropa,40913.540000,5.0,Shopify,Lima,Tarjeta crédito,204567.70,28/02/2024
1029,2030,2024-06-14,NaN,Ropa,13680.800000,1.0,Shopify,Ciudad de México,Tarjeta débito,13680.80,14/06/2024
1227,2228,2024-12-21,NaN,Ropa,24182.020000,1.0,WooCommerce,Madrid,Tarjeta crédito,24182.02,21/12/2024
1246,2247,2024-02-10,NaN,Ropa,74639.830000,3.0,MercadoLibre,Córdoba,Tarjeta crédito,223919.49,10/02/2024
1546,2547,2024-12-06,NaN,Ropa,35671.710000,4.0,MercadoLibre,Córdoba,Tarjeta débito,142686.84,06/12/2024
1548,2549,2024-07-10,NaN,Accesorios,16408.520000,5.0,WooCommerce,Mar del Plata,Transferencia,82042.60,10/07/2024
1586,2587,2024-06-28,NaN,Accesorios,8316.430000,1.0,MercadoLibre,Mendoza,Transferencia,8316.43,28/06/2024
1701,2702,2024-10-21,NaN,Accesorios,25399.450000,4.0,Shopify,Córdoba,Efectivo,101597.80,21/10/2024
1806,2807,2024-08-31,NaN,Ropa,19868.250000,3.0,MercadoLibre,Lima,Efectivo,59604.75,31/08/2024
1898,2899,2024-12-04,NaN,Ropa,35743.870000,2.0,Shopify,Bogotá,Tarjeta crédito,71487.74,04/12/2024
1970,2971,2024-02-11,NaN,Accesorios,24461.050000,1.0,Tiendanube,Rosario,Tarjeta débito,24461.05,11/02/2024
2063,3064,2024-06-22,NaN,Ropa,37356.890000,2.0,MercadoLibre,Santiago,Tarjeta crédito,74713.78,22/06/2024
2118,3119,2024-05-30,NaN,Ropa,52926.000000,3.0,Shopify,Mar del Plata,Transferencia,158778.00,30/05/2024
2126,3127,2024-08-16,NaN,Accesorios,26275.190000,3.0,WooCommerce,Mar del Plata,Tarjeta débito,78825.57,16/08/2024
2187,3188,2024-10-14,NaN,Accesorios,24155.180000,4.0,MercadoLibre,Mar del Plata,Tarjeta débito,96620.72,14/10/2024
2228,3229,2024-05-01,NaN,Ropa,35313.340000,4.0,WooCommerce,Ciudad de México,Tarjeta débito,141253.36,01/05/2024
2253,3254,2024-08-18,NaN,Ropa,40583.060000,1.0,MercadoLibre,Lima,Transferencia,40583.06,18/08/2024
2661,3662,2024-07-26,NaN,Accesorios,-3002.925209,2.0,Shopify,Lima,Efectivo,48287.52,26/07/2024
2954,3955,2024-07-02,NaN,Ropa,67342.060000,1.0,WooCommerce,Santiago,Tarjeta débito,67342.06,02/07/2024
3011,4012,2024-01-04,NaN,Ropa,54446.790000,4.0,Shopify,Mar del Plata,Transferencia,217787.16,04/01/2024
3083,4084,2024-01-05,NaN,Ropa,67451.620000,1.0,MercadoLibre,Ciudad de México,Tarjeta débito,67451.62,05/01/2024
3199,4200,2024-06-15,NaN,Accesorios,27425.760000,3.0,Shopify,Rosario,Tarjeta crédito,82277.28,15/06/2024
3329,4330,2024-11-26,NaN,Ropa,54473.150000,3.0,MercadoLibre,Buenos Aires,Transferencia,163419.45,26/11/2024
3373,4374,2024-08-31,NaN,Accesorios,18363.370000,4.0,WooCommerce,Mendoza,Transferencia,73453.48,31/08/2024
3645,4646,2024-03-04,NaN,Accesorios,19106.110000,2.0,WooCommerce,NaN,Efectivo,38212.22,04/03/2024
3694,4695,2024-12-21,NaN,Ropa,24100.360000,2.0,MercadoLibre,Lima,Tarjeta crédito,48200.72,21/12/2024
3796,4797,2024-11-17,NaN,Ropa,38150.810000,4.0,Tiendanube,Buenos Aires,Tarjeta débito,152603.24,17/11/2024
3863,4864,2024-09-25,NaN,Accesorios,8522.520000,1.0,MercadoLibre,Buenos Aires,Tarjeta crédito,8522.52,25/09/2024
3881,4882,2024-02-22,NaN,Accesorios,7861.820000,3.0,MercadoLibre,Buenos Aires,Tarjeta crédito,23585.46,22/02/2024
4067,5068,2024-05-12,NaN,Ropa,39788.410000,5.0,WooCommerce,Santiago,Tarjeta débito,198942.05,12/05/2024
4281,5282,2024-08-02,NaN,Ropa,44557.080000,2.0,Shopify,Rosario,Transferencia,89114.16,02/08/2024
4322,5323,2024-08-10,NaN,Ropa,24002.860000,1.0,Shopify,Bogotá,Efectivo,24002.86,10/08/2024
4344,5345,2024-03-19,NaN,Accesorios,8208.730000,3.0,WooCommerce,Bogotá,Tarjeta crédito,24626.19,19/03/2024
4383,5384,2024-08-13,NaN,Ropa,39901.460000,1.0,MercadoLibre,Santiago,Tarjeta débito,39901.46,13/08/2024
4453,5454,2024-11-15,NaN,Calzado,83224.140000,3.0,Tiendanube,Bogotá,Tarjeta crédito,249672.42,15/11/2024
4603,5604,2024-05-20,NaN,Ropa,58220.390000,4.0,WooCommerce,Lima,Tarjeta débito,232881.56,20/05/2024
4698,5699,2024-05-13,NaN,Ropa,22221.970000,4.0,MercadoLibre,Madrid,Tarjeta crédito,88887.88,13/05/2024
4758,5759,2024-09-30,NaN,Calzado,91139.970000,5.0,Tiendanube,Santiago,Transferencia,455699.85,30/09/2024
4809,5810,2024-07-06,NaN,Ropa,20481.100000,3.0,Shopify,Madrid,Tarjeta crédito,61443.30,06/07/2024
4952,5953,2024-07-13,NaN,Accesorios,24948.380000,3.0,WooCommerce,Rosario,Tarjeta crédito,74845.14,13/07/2024

In [7]:
### valido los nombres de los productos, y hago una referencia de estos productos agrupandolos por categoria y producto y haciendo la mediana de los mismos para restar.

validos = ["Remera básica", "Jean slim", "Zapatillas running", "Campera impermeable",
           "Vestido floral", "Short deportivo", "Buzo hoodie", "Medias pack x3",
           "Gorra snapback", "Cinturón cuero"]

ref = (
    df[df["producto"].isin(validos)]
    .groupby(["categoria","producto"])["precio_unitario"]
    .median()
)

ref

categoria   producto
Accesorios  Cinturón cuero         24747.640
            Gorra snapback         17900.380
            Medias pack x3          7979.570
Calzado     Zapatillas running     84419.450
Ropa        Buzo hoodie            55215.260
            Campera impermeable    71834.930
            Jean slim              44990.340
            Remera básica          14970.900
            Short deportivo        22047.870
            Vestido floral         37797.355
Name: precio_unitario, dtype: float64

In [8]:
# Hago un bucle for para recorrer las filas de los productos nulos, encontrar el precio de esos productos, restarles el precio con los precios de las medianas de la referencia, y los que son mas bajos (mas cercano a 0) reemplazo el nombre del producto en el nan. 

for i, prod in df_productos_nulos.iterrows():
    categoria = prod["categoria"]
    precio = prod["precio_unitario"]
    candidatos = ref.loc[categoria]
    
    precio_cercano = candidatos - precio
    
    ganador = precio_cercano.abs().idxmin()
    
    df.loc[i, "producto"] = ganador

In [9]:
df["producto"].unique()

<ArrowStringArray>
[     'Gorra snapback',       'Remera básica',      'Vestido floral',
  'Zapatillas running',      'Cinturón cuero',         'Buzo hoodie',
           'Jean slim',     'Short deportivo', 'Campera impermeable',
           'JEAN SLIM',      'Medias pack x3',       'Remera basica',
 'campera Impermeable',  'zapatillas running']
Length: 14, dtype: str

In [10]:

#normalizo los nombres de los productos poniendo en minusculas. 
productos_normalizado = {
    'Gorra snapback':'Gorra snapback',
    'Remera básica': 'Remera basica',
    'Vestido floral':"vestido floral",
    'Zapatillas running':'zapatillas running',
    'Cinturón cuero':"cinturon cuero",
    'Buzo hoodie' :"buzo hoodie",
    'JEAN SLIM':'Jean slim',
    'Short deportivo' : "short deportivo",
    'Medias pack x3' : "medias pack x3",
    'Campera impermeable':'campera Impermeable',
}


df["producto"] = df["producto"].replace(productos_normalizado).str.lower()

df["producto"].unique()

<ArrowStringArray>
[     'gorra snapback',       'remera basica',      'vestido floral',
  'zapatillas running',      'cinturon cuero',         'buzo hoodie',
           'jean slim',     'short deportivo', 'campera impermeable',
      'medias pack x3']
Length: 10, dtype: str

### Corrección datos nulos en cantidad

In [11]:
df.shape

(5100, 11)

In [12]:
cantidad_null_negativo = df.loc[(df["cantidad"]<=0) | (df["cantidad"].isna())]
filas_cantidad_null_negativo = len(cantidad_null_negativo)

if filas_cantidad_null_negativo < df.shape[0] * 0.1:
    df = df[df["cantidad"] > 0]
    df=df.dropna(subset="cantidad")
    print(f"Filas eliminadas: {filas_cantidad_null_negativo}, por elemenos nulos o negativos, menos del 10% del dataset.")
else:
    print(f"Cantidad erronea alta. ({df.shape[0] / filas_cantidad_null_negativo}), revisar el dataset.")

Filas eliminadas: 61, por elemenos nulos o negativos, menos del 10% del dataset.

### Corrección de Canal

In [13]:
# el canal son 50 elementos que son nulos, podemos optar por poner que se compraron en tienda fisica. 

df["canal"] = df["canal"].fillna("tienda fisica")

In [14]:
df["canal"].isnull().sum()

np.int64(0)

### Corrección de Ciudad

In [15]:
# Al no saber la ciudad podemos poner que desconocido

df["ciudad"] = df["ciudad"].fillna("desconocido")

In [16]:
df["ciudad"].isnull().sum()

np.int64(0)

### Corrección de Metodo de Pago

In [17]:
# son 50 elementos que se desconoce el metodo de pago, es el 1% del dataset, podemos optar por dropearlo.

df = df.dropna(subset=["metodo_pago"])

In [18]:
df["metodo_pago"].isnull().sum()

np.int64(0)

In [19]:
df.isnull().sum()

id_orden           0
fecha              0
producto           0
categoria          0
precio_unitario    0
cantidad           0
canal              0
ciudad             0
metodo_pago        0
total_venta        0
fecha_str          0
dtype: int64

In [20]:
#Eliminados todos los nulos, me queda por hacer, convertir todos los valores en minusculas, eliminar los espacios vacios con strip, modificar tipo de fecha con datetime.

### Conversión de fecha

In [21]:
df["fecha"] = pd.to_datetime(df["fecha"])

In [22]:
df.info()

<class 'pandas.DataFrame'>
Index: 4990 entries, 0 to 5099
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_orden         4990 non-null   int64
 1   fecha            4990 non-null   datetime64[us]
 2   producto         4990 non-null   str
 3   categoria        4990 non-null   str
 4   precio_unitario  4990 non-null   float64
 5   cantidad         4990 non-null   float64
 6   canal            4990 non-null   str
 7   ciudad           4990 non-null   str
 8   metodo_pago      4990 non-null   str
 9   total_venta      4990 non-null   float64
 10  fecha_str        4990 non-null   str
dtypes: datetime64[us](1), float64(3), int64(1), str(6)
memory usage: 782.0 KB

In [23]:

for fecha in df["fecha_str"]:
    if fecha is None:
        fecha = fecha.replace("fecha_invalida")

### normalización de columnas

In [24]:
for columna in df.columns:
    columna.lower().strip().replace(" ","_")
    print(columna)

id_orden
fecha
producto
categoria
precio_unitario
cantidad
canal
ciudad
metodo_pago
total_venta
fecha_str

### Precios

In [25]:
df.shape

(4990, 11)

In [26]:
# Trato de precios, si los precios son menores a 0 es incorrecto, eliminar o solucionarlos.

precios_negativos = df[df["precio_unitario"] <= 0]
filas_precios_negativos = len(precios_negativos)
filas_df = len(df)


if filas_precios_negativos < (filas_df * 0.1):
    df = df[df["precio_unitario"] > 0]
    print(f"Filas descartadas: {filas_precios_negativos}")
else:
    print(f"Demasiados precios inválidos ({filas_precios_negativos} / {filas_df}). Revisar el archivo.")

Filas descartadas: 81

In [27]:
df.shape

(4909, 11)

### Filas duplicadas

In [28]:
df = df.drop_duplicates()
df.shape

(4819, 11)